builders:
  navigation_builder:
    import: "package:navigation_generator/builders/builder.dart"
    builder_factories: ["navigationBuilder"]
    build_extensions: {"lib/$lib$": ["lib/output.dart"]}
    auto_apply: root_package
    build_to: source