builders:
  route_builder:
    import: "package:route_generator/builders/builder.dart"
    builder_factories: ["routeBuilder"]
    build_extensions: {"lib/$lib$": ["lib/output.dart"]}
    auto_apply: root_package
    build_to: source